### ISSUE TITLE
Changing of Background

### ISSUE THREAD

**Issue by gautamjajoo** [gautamjajoo/Registeration-Form#1]
Changing of Background matching to the menu bar colour- Blue #

**Comment by braglin** [comment]
Hi man,

Do you really want to keep this menu color?

Take a look at this, if you agree I will made a PR.

![menu](https://user-images.githubusercontent.com/14234364/31839354-7d0fceaa-b5bf-11e7-9494-df89e6739baf.png)

**Comment by vijayakumarGit** [comment]
I need some clarification about this issue @gautamjajoo
